### ISSUE TITLE
一番上のレイヤーがロックされている際のエラー

### ISSUE THREAD

**Issue by shspage** [gau/reshape-to-symmetrical-segment#1]
一番上のレイヤーがロックされていると、基準線などの描画でエラーになるようです。
選択オブジェクトのあるレイヤーに描画するとよいと思います。

例：
var targetLayer = app.activeDocument.selection[0].layer;
...
activeDocument.pathItems.add();
→ targetLayer.pathItems.add()

activeDocument.pathItems.ellipse(...
→ targetLayer.pathItems.ellipse(...

**Comment by gau** [comment]
ご指摘ありがとうございます！
確かにそうでした（いつも忘れてしまいます）。
0.5.3で修正しました

**Comment by shspage** [comment]
ご対応ありがとうございます！
ではこちらはCloseします。

**Comment by gau** [comment]
ご指摘ありがとうございました！
